// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJfVJ4mDCBboIoMopH1hksAbsXm0hecbg',
    appId: '1:333796334585:web:b9d563f31f634dba0afb28',
    messagingSenderId: '333796334585',
    projectId: 'pruebaagroaqui',
    authDomain: 'pruebaagroaqui.firebaseapp.com',
    storageBucket: 'pruebaagroaqui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn63vsjNxvTia444O-wkWAmN2gI9NuoB8',
    appId: '1:333796334585:android:7a3b36092252d9340afb28',
    messagingSenderId: '333796334585',
    projectId: 'pruebaagroaqui',
    storageBucket: 'pruebaagroaqui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkK23XDUw9UFKgw-EG7f48eABzp40Ift0',
    appId: '1:333796334585:ios:c4f23131dd3f75fc0afb28',
    messagingSenderId: '333796334585',
    projectId: 'pruebaagroaqui',
    storageBucket: 'pruebaagroaqui.appspot.com',
    androidClientId: '333796334585-20ldqav06t4he6p7sue8qlo6dndhfsvr.apps.googleusercontent.com',
    iosClientId: '333796334585-1uosfr9fu2u2eoo6hrgra5b3qlprjeqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroaquivr1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkK23XDUw9UFKgw-EG7f48eABzp40Ift0',
    appId: '1:333796334585:ios:c4f23131dd3f75fc0afb28',
    messagingSenderId: '333796334585',
    projectId: 'pruebaagroaqui',
    storageBucket: 'pruebaagroaqui.appspot.com',
    androidClientId: '333796334585-20ldqav06t4he6p7sue8qlo6dndhfsvr.apps.googleusercontent.com',
    iosClientId: '333796334585-1uosfr9fu2u2eoo6hrgra5b3qlprjeqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroaquivr1',
  );
}
